@Library('GissFwDevOps@V5') _

FwDevOps("java21maven-3.9",
	[
	"TOOLS_DEPLOY":"HELM",
	"CODE_REVIEW":"true",
	"UNIT_TEST":"true",
	"COMPILABLES": "java",
	"CD": "true",
	"FW_CLIENT":"Devops FW"
    ]
)
